package asterixorobelix.routedetail.ui.detail.models.api

import com.google.gson.annotations.SerializedName

data class RouteDetail(
	@SerializedName("id") val id: Int,
	@SerializedName("slug") val slug: String,
	@SerializedName("user_id") val user_id: Int,
	@SerializedName("user") val user: User,
	@SerializedName("primary_language") val primary_language: String,
	@SerializedName("name") val name: String,
	@SerializedName("description") val description: String,
	@SerializedName("polyline") val polyline: String,
	@SerializedName("distance") val distance: Int,
	@SerializedName("duration") val duration: Int,
	@SerializedName("days") val days: Int,
	@SerializedName("camping_count") val camping_count: Int,
	@SerializedName("privacy") val privacy: String,
	@SerializedName("photo") val photo: Photo,
	@SerializedName("refresh_date") val refresh_date: String,
	@SerializedName("created_at") val created_at: String,
	@SerializedName("updated_at") val updated_at: String,
	@SerializedName("last_updated_diff_for_humans") val last_updated_diff_for_humans: String,
	@SerializedName("default_view") val default_view: String,
	@SerializedName("map") val map: String,
	@SerializedName("map_square") val map_square: String,
	@SerializedName("map_small") val map_small: String,
	@SerializedName("editable") val editable: Boolean,
	@SerializedName("favorited") val favorited: Boolean,
	@SerializedName("liked") val liked: Boolean,
	@SerializedName("comments_count") val comments_count: Int,
	@SerializedName("like_count") val like_count: Int,
	@SerializedName("favorite_count") val favorite_count: Int,
	@SerializedName("share_url") val share_url: String,
	@SerializedName("waypoint_count") val waypoint_count: Int,
	@SerializedName("geo_waypoint_count") val geo_waypoint_count: Int,
	@SerializedName("featured") val featured: Boolean,
	@SerializedName("url") val url: String,
	@SerializedName("relative_url") val relative_url: String,
	@SerializedName("relative_story_url") val relative_story_url: String,
	@SerializedName("popularity_count") val popularity_count: Int,
	@SerializedName("regions") val regions: List<Int>,
	@SerializedName("de") val de: De,
	@SerializedName("nl") val nl: Nl,
	@SerializedName("en") val en: En,
	@SerializedName("waypoints") val waypoints: List<Waypoints>
)